config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  # has_many :sub_tasks

  validates :title, presence: true
end

app/models/sub_task.rb
class SubTask < ApplicationRecord
  # belongs_to :post

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all
    require "date"
    @date_today = Date.today
    @posts_today = Post.where(due_date: Date.today)
  end

  def show
  end

  def new
    @post = Post.new
  end
  
  def create
    @post = Post.create(post_params)

    if @post.save
      # flash[:success] = "タスクが投稿されました"
      redirect_to root_path
    else
      # flash[:danger] = "タスクが投稿されません"
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :due_date, :memo).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
  
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title MyPlan
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'posts/header'
    = yield

app/views/posts/_header.html.haml
.post
  .header
    .left-header
      = link_to root_path do
        %i.fa.fa-home.fa-2x
      .form
        = form_tag posts_path, method: :get do
          = text_field_tag :body, '', class: 'form__input'
          = submit_tag '検索', class: 'form__btn'
    %ul.lists
      -if user_signed_in?
        %li.my-page
          = link_to "マイページ", user_path(current_user)
        %li.logout
          = link_to "ログアウト", destroy_user_session_path, method: :delete
      - else
        %li.login
          = link_to 'ログイン', new_user_session_path
        %li.sign-up
          = link_to '新規登録', new_user_registration_path

app/views/posts/_main.html.haml
.main
  .main__content
    全てのタスク
  .main__action
    .main__action__plan
      %ul.tasks
        - @posts.each do |post|
          %li.task
            .task-left
              .task-left__top
                .task-left__top__button
                  = check_box_tag :check1
                .task-left__top__title
                  = post.title
              .task-left__date
                = post.due_date
            .task-right
              - if user_signed_in? && current_user.id == post.user_id
                .task-right__edit
                  = link_to '編集', edit_post_path(post)
                .task-right__delete
                  = link_to '削除', post_path(post), method: :delete
              - else
                .task-right__detail
                  = link_to '詳細', post_path(post)
      .add-task
      = link_to '＋　タスクを追加', new_post_path, class: "task-link"

app/views/posts/_sidebar.html.haml
.side-bar
  %ul
    %li
      = link_to "タスク一覧", root_path
    %li
      自分の投稿
    %li
      今日
    %li
      優先度 1
    %li
      優先度 2
    %li
      優先度 3
    %li
      優先度 4
    %li
      予定日なし

app/views/posts/_today.html.haml
.main
  .main__content
    今日
  .main__action
    .main__action__plan
      %ul.tasks
        - @post_today.each do |post|
          %li.task
            .task-left
              .task-left__top
                .task-left__top__button
                  = check_box_tag :check1
                .task-left__top__title
                  = post.title
              .task-left__date
                = post.due_date
            .task-right
              - if user_signed_in? && current_user.id == post.user_id
                .task-right__edit
                  = link_to '編集', edit_post_path(post)
                .task-right__delete
                  = link_to '削除', post_path(post), method: :delete
              - else
                .task-right__detail
                  = link_to '詳細', post_path(post)
      .add-task
      = link_to '＋　タスクを追加', new_post_path, class: "task-link"

app/views/posts/edit.html.haml
.new-task
  = form_for @post do |f|
    .task
      %p.task__paragraph1 タスク
      = f.text_field :title, class: "task__form"
    .date
      %p.date__paragraph2 期日
      = f.date_select :due_date, class: "date__deadline"
    -# .sub-task
    -#   %p.sub-task__paragraph3 サブタスク
    -#   = f.fields_for :sub_tasks do |t|
    -#     = t.text_field :task, class: "sub-task__form"
    .memo
      %p.memo__paragraph4 メモ
      = f.text_area :memo, class: "memo__form"
    .add-btn
      = f.submit "変更する", class: "task-btn"

app/views/posts/index.html.haml
.wrapper
  = render "sidebar"
  = render "main"

app/views/posts/new.html.haml
.new-task
  = form_for @post do |f|
    .task
      %p タスク
      = f.text_field :title, class: "task__form"
    .date
      %p 期日
      = f.date_select :due_date, class: "date__deadline"
    -# .sub-task
    -#   %p サブタスク
    -#   = f.fields_for :sub_tasks do |t|
    -#     = t.text_field :task, class: "sub-task__form"
    .memo
      %p メモ
      = f.text_area :memo, class: "memo__form"
    .add-btn
      = f.submit "投稿する", class: "task-btn"
      -# %button.task-btn{type: "submit", method: "post"}
      -#   投稿

app/views/posts/show.html.haml
.new-task
  .task
    %p.task__paragraph1 タスク
    .task__title
      = @post.title
  .date
    %p.date__paragraph2 期日
    .date__detail
      = @post.due_date
  .memo
    %p.memo__paragraph4 メモ
    .memo__detail
      = @post.memo

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", '#', class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/show.html.haml
.wrapper
  = render "posts/sidebar"
  = render "posts/main"